// packages/demo-react/src/App.tsx
import { useState, useMemo, useCallback, useEffect, useRef } from 'react'
import { latexToHtml, latexToSvg, htexPaginate } from '@htex/core'
import EXAMPLE from './example.tex?raw'

type Format     = 'html' | 'svg'
type Theme      = 'light' | 'dark'
type RenderMode = 'paged' | 'canvas'

// ── Pill (segmented control) ──────────────────────────────────────────────
function Pill<T extends string>({ options, value, onChange, accent = '#238636' }: {
  options: { label: string; value: T }[]
  value: T; onChange: (v: T) => void; accent?: string
}) {
  return (
    <div style={{ display:'flex', background:'#161b22', borderRadius:5,
      padding:2, border:'1px solid #30363d', gap:1 }}>
      {options.map(o => (
        <button key={o.value} onClick={() => onChange(o.value)} style={{
          padding:'0.15rem 0.55rem', border:'none', borderRadius:3,
          fontSize:'0.7rem', fontWeight:600, cursor:'pointer',
          background: value === o.value ? accent : 'transparent',
          color: value === o.value ? '#fff' : '#8b949e',
          transition:'all 0.1s', whiteSpace:'nowrap',
        }}>{o.label}</button>
      ))}
    </div>
  )
}

export default function App() {
  const [source,     setSource]     = useState<string>(EXAMPLE)
  const [format,     setFormat]     = useState<Format>('html')
  const [theme,      setTheme]      = useState<Theme>('light')
  const [renderMode, setRenderMode] = useState<RenderMode>('paged')
  const [fileName,   setFileName]   = useState('')
  const [isDragging, setIsDragging] = useState(false)
  const [copied,     setCopied]     = useState(false)
  const [renderTime, setRenderTime] = useState(0)
  const [zoom,       setZoom]       = useState(() => {
    const stored = localStorage.getItem('htex-zoom')
    return stored ? parseInt(stored) : 100
  })
  const previewRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)

  const { rendered, error } = useMemo(() => {
    if (!source.trim()) return { rendered: '', error: '' }
    const t0 = performance.now()
    try {
      const out = format === 'svg'
        ? latexToSvg(source, { theme, standalone: false })
        : latexToHtml(source, { theme, standalone: false,
            diagramBaseUrl: '/diagrams', renderMode })
      setRenderTime(Math.round(performance.now() - t0))
      return { rendered: out, error: '' }
    } catch (e) {
      return { rendered: '', error: e instanceof Error ? e.message : String(e) }
    }
  }, [source, format, theme, renderMode])

  // After HTML is injected into the DOM, call the SDK paginator.
  // htexPaginate() is idempotent — it only acts on [data-htex-unpaginated] elements.
  useEffect(() => {
    if (format === 'html' && renderMode === 'paged' && rendered && previewRef.current) {
      htexPaginate(previewRef.current)
    }
  }, [rendered, format, renderMode])

  // Keyboard shortcuts for zoom
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.ctrlKey || e.metaKey) {
        if (e.key === '+' || e.key === '=') {
          e.preventDefault()
          setZoom(z => {
            const newZoom = Math.min(z + 10, 200)
            localStorage.setItem('htex-zoom', String(newZoom))
            return newZoom
          })
        } else if (e.key === '-') {
          e.preventDefault()
          setZoom(z => {
            const newZoom = Math.max(z - 10, 50)
            localStorage.setItem('htex-zoom', String(newZoom))
            return newZoom
          })
        } else if (e.key === '0') {
          e.preventDefault()
          setZoom(100)
          localStorage.setItem('htex-zoom', '100')
        }
      }
    }
    window.addEventListener('keydown', handleKeyDown)
    return () => window.removeEventListener('keydown', handleKeyDown)
  }, [])

  const handleZoom = useCallback((delta: number) => {
    setZoom(z => {
      const newZoom = Math.max(50, Math.min(200, z + delta))
      localStorage.setItem('htex-zoom', String(newZoom))
      return newZoom
    })
  }, [])

  const onDragOver  = useCallback((e: React.DragEvent) => { e.preventDefault(); setIsDragging(true) }, [])
  const onDragLeave = useCallback((e: React.DragEvent) => {
    if (!e.currentTarget.contains(e.relatedTarget as Node)) setIsDragging(false)
  }, [])
  const onDrop = useCallback(async (e: React.DragEvent) => {
    e.preventDefault(); setIsDragging(false)
    const f = e.dataTransfer?.files?.[0]; if (!f) return
    setFileName(f.name); setSource(await f.text())
  }, [])
  const onFileInput = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0]; if (!f) return
    setFileName(f.name); setSource(await f.text())
  }, [])
  const download = useCallback(() => {
    if (!rendered) return
    const ext  = format === 'svg' ? 'svg' : 'html'
    const mime = format === 'svg' ? 'image/svg+xml' : 'text/html'
    const full = format === 'html'
      ? latexToHtml(source, { theme, standalone: true,
          diagramBaseUrl: '/diagrams', renderMode })
      : latexToSvg(source, { theme, standalone: true })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(new Blob([full], { type: mime }))
    a.download = (fileName.replace(/\.[^.]+$/, '') || 'document') + '.' + ext
    a.click(); URL.revokeObjectURL(a.href)
  }, [rendered, format, source, theme, fileName, renderMode])
  const copyOutput = useCallback(async () => {
    if (!rendered) return
    await navigator.clipboard.writeText(rendered)
    setCopied(true); setTimeout(() => setCopied(false), 1500)
  }, [rendered])

  const dark = '#0d1117', border = '#21262d', muted = '#6e7681'
  const previewLabel = format === 'html'
    ? (renderMode === 'paged' ? 'PAGES' : 'CANVAS')
    : 'SVG'
  const previewBg = (format === 'html' && renderMode === 'paged') ? '#525659' : '#ffffff'

  return (
    <div style={{ display:'grid', gridTemplateRows:'48px 1fr', height:'100vh', overflow:'hidden',
      background:'#0f1117', color:'#e2e8f0',
      fontFamily:'-apple-system,BlinkMacSystemFont,"Segoe UI",system-ui,sans-serif' }}>
      {/* ── Header ── */}
      <header style={{ display:'flex', alignItems:'center', gap:'0.75rem',
        padding:'0 1rem', background:dark, borderBottom:`1px solid ${border}`,
        overflow:'hidden', flexShrink:0 }}>
        <div style={{ fontSize:'1rem', fontWeight:800, letterSpacing:'-0.5px',
          color:'#f0f6fc', whiteSpace:'nowrap', flexShrink:0 }}>
          htex <span style={{ fontWeight:400, color:'#8b949e', fontSize:'0.9em' }}>/&nbsp;react</span>
        </div>
        <span style={{ fontSize:'0.6rem', fontWeight:700, padding:'0.1rem 0.4rem',
          borderRadius:3, background:'#3b1d5f', color:'#d2a8ff', flexShrink:0 }}>
          React 19 · Hooks
        </span>
        {source.trim() && <span style={{ fontSize:'0.7rem', color:muted, whiteSpace:'nowrap' }}>
          {renderTime}ms · {source.length.toLocaleString()} chars
        </span>}
        <div style={{ flex:1 }} />
        <div style={{ display:'flex', gap:'0.4rem', alignItems:'center', flexShrink:0 }}>
          <Pill options={[{label:'HTML',value:'html'},{label:'SVG',value:'svg'}]}
            value={format} onChange={setFormat} accent="#1f6feb" />
          {format === 'html' && (
            <Pill<RenderMode>
              options={[{label:'Canvas',value:'canvas'},{label:'Pages',value:'paged'}]}
              value={renderMode} onChange={setRenderMode} accent="#7c3aed" />
          )}
          <Pill options={[{label:'Light',value:'light'},{label:'Dark',value:'dark'}]}
            value={theme} onChange={setTheme} />
          <button disabled={!rendered} onClick={copyOutput} style={{
            padding:'0.2rem 0.65rem', borderRadius:5, border:`1px solid ${border}`,
            background:'#21262d', color: rendered ? '#c9d1d9' : muted,
            fontSize:'0.7rem', fontWeight:600, cursor: rendered ? 'pointer':'default',
            whiteSpace:'nowrap', opacity: rendered ? 1 : 0.35 }}>
            {copied ? '✓ Copied' : '⎘ Copy'}
          </button>
          <button disabled={!rendered} onClick={download} style={{
            padding:'0.2rem 0.65rem', borderRadius:5, border:'1px solid #1f6feb',
            background:'#1f6feb', color: rendered ? '#fff' : muted,
            fontSize:'0.7rem', fontWeight:600, cursor: rendered ? 'pointer':'default',
            whiteSpace:'nowrap', opacity: rendered ? 1 : 0.35 }}>
            ↓ {format.toUpperCase()}
          </button>
        </div>
      </header>
      {/* ── Workspace ── */}
      <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', overflow:'hidden', minHeight:0 }}>
        {/* Left: editor */}
        <div style={{ display:'flex', flexDirection:'column', overflow:'hidden',
          borderRight:`1px solid ${border}`, minHeight:0 }}
          onDragOver={onDragOver} onDragLeave={onDragLeave} onDrop={onDrop}>
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between',
            padding:'0 0.75rem', height:32, background:dark, borderBottom:`1px solid ${border}`,
            fontSize:'0.65rem', fontWeight:700, color:muted,
            textTransform:'uppercase', letterSpacing:'0.08em', flexShrink:0 }}>
            LaTeX Source
            {fileName && <span style={{ background:'#1f3a5f', color:'#79c0ff',
              padding:'0.08rem 0.35rem', borderRadius:3, fontSize:'0.62rem',
              fontWeight:600, textTransform:'none', letterSpacing:0 }}>📄 {fileName}</span>}
          </div>
          <div style={{ padding:'0 0.75rem', height:28, display:'flex', alignItems:'center',
            gap:'0.5rem', background:dark, borderBottom:`1px solid ${border}`,
            fontSize:'0.68rem', color:muted, flexShrink:0 }}>
            📂 Drop a <code style={{ fontFamily:'monospace', color:'#8b949e' }}>.tex</code> file, or&nbsp;
            <label style={{ color:'#58a6ff', cursor:'pointer', fontWeight:600 }}>
              browse<input type="file" accept=".tex,.txt" style={{ display:'none' }} onChange={onFileInput}/>
            </label>
          </div>
          <div style={{ position:'relative', flex:1, overflow:'hidden', minHeight:0 }}>
            {isDragging && (
              <div style={{ position:'absolute', inset:0, background:'rgba(31,111,235,0.12)',
                border:'2px dashed #1f6feb', display:'flex', alignItems:'center',
                justifyContent:'center', fontSize:'1rem', fontWeight:700,
                color:'#58a6ff', zIndex:10, pointerEvents:'none' }}>
                Drop .tex file here
              </div>
            )}
            <textarea value={source} onChange={e => setSource(e.target.value)}
              placeholder="Paste or type LaTeX here…" spellCheck={false}
              autoCorrect="off" autoCapitalize="off"
              style={{ width:'100%', height:'100%', background:dark, border:'none',
                outline:'none', resize:'none', padding:'0.75rem 1rem',
                fontFamily:"'Fira Code','Cascadia Code','JetBrains Mono','SF Mono',monospace",
                fontSize:'0.78rem', lineHeight:1.6, color:'#c9d1d9', tabSize:2 }}
            />
          </div>
        </div>
        {/* Right: preview */}
        <div style={{ display:'flex', flexDirection:'column', overflow:'hidden',
          minHeight:0, background: previewBg, transition:'background 0.15s' }}>
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between',
            padding:'0 0.75rem', height:32, background:dark, borderBottom:`1px solid ${border}`,
            fontSize:'0.65rem', fontWeight:700, color:muted,
            textTransform:'uppercase', letterSpacing:'0.08em', flexShrink:0 }}>
            <div style={{ display:'flex', alignItems:'center', gap:'0.5rem' }}>
              <span>Preview — {previewLabel}</span>
              {fileName && <span style={{ background:'#2d1b4e', color:'#d2a8ff',
                padding:'0.08rem 0.35rem', borderRadius:3, fontSize:'0.62rem',
                fontWeight:600, textTransform:'none' }}>{fileName}</span>}
            </div>
            {format === 'html' && (
              <div style={{ display:'flex', alignItems:'center', gap:'0.3rem' }}>
                <button onClick={() => handleZoom(-10)} 
                  style={{ padding:'0.15rem 0.35rem', borderRadius:3, border:`1px solid ${border}`,
                    background:'transparent', color:muted, fontSize:'0.65rem', fontWeight:600,
                    cursor:'pointer', transition:'all 0.1s' }}
                  title="Zoom out (Ctrl+-)">−</button>
                <span style={{ fontSize:'0.65rem', color:muted, minWidth:'2.5rem', textAlign:'center' }}>
                  {zoom}%
                </span>
                <button onClick={() => handleZoom(10)} 
                  style={{ padding:'0.15rem 0.35rem', borderRadius:3, border:`1px solid ${border}`,
                    background:'transparent', color:muted, fontSize:'0.65rem', fontWeight:600,
                    cursor:'pointer', transition:'all 0.1s' }}
                  title="Zoom in (Ctrl++)">+</button>
                <button onClick={() => { setZoom(100); localStorage.setItem('htex-zoom', '100') }}
                  style={{ padding:'0.15rem 0.35rem', borderRadius:3, border:`1px solid ${border}`,
                    background:'transparent', color:muted, fontSize:'0.65rem', fontWeight:600,
                    cursor:'pointer', transition:'all 0.1s' }}
                  title="Reset zoom (Ctrl+0)">100</button>
              </div>
            )}
          </div>
          <div style={{ flex:1, overflow:'auto', minHeight:0 }}>
            {error ? (
              <div style={{ background:'rgba(248,81,73,0.1)', border:'1px solid rgba(248,81,73,0.3)',
                borderRadius:6, padding:'1rem', color:'#ff7b72', fontFamily:'monospace',
                fontSize:'0.8rem', whiteSpace:'pre-wrap', lineHeight:1.5,
                maxWidth:760, margin:'2rem auto' }}>
                ⚠ Render error:{'\n\n'}{error}
              </div>
            ) : rendered ? (
              format === 'svg' ? (
                <div style={{ padding:'2rem', background:'#404040', minHeight:'100%',
                  display:'flex', flexDirection:'column', alignItems:'center' }}
                  dangerouslySetInnerHTML={{ __html: rendered }}
                />
              ) : (
                <div style={{ 
                  flex: 1,
                  overflow: 'auto',
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',
                  padding: '2rem 0'
                }}>
                  <div style={{
                    transformOrigin: '0 0',
                    transform: `scale(${zoom / 100})`,
                    transition: 'transform 0.15s ease-out',
                    willChange: 'transform'
                  }}>
                    <div ref={previewRef} style={{ width: '608px' }}
                      dangerouslySetInnerHTML={{ __html: rendered }}
                    />
                  </div>
                </div>
              )
            ) : (
              <div style={{ display:'flex', flexDirection:'column', alignItems:'center',
                justifyContent:'center', height:'100%', minHeight:300, gap:'0.5rem', color:'#888' }}>
                <div style={{ fontSize:'2rem' }}>⚛</div>
                <div style={{ fontSize:'0.8rem' }}>Rendered document appears here</div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}

// packages/demo-svelte/src/App.svelte
<script lang="ts">
  import { latexToHtml, latexToSvg, htexPaginate } from '@htex/core'
  import EXAMPLE from './example.tex?raw'

  // ── State ─────────────────────────────────────────────────────────────────
  let source      = $state(EXAMPLE)
  let format      = $state<'html' | 'svg'>('html')
  let theme       = $state<'light' | 'dark'>('light')
  let renderMode  = $state<'paged' | 'canvas'>('paged')
  let isDragging  = $state(false)
  let fileName    = $state('')
  let copied      = $state(false)
  let previewEl   = $state<HTMLElement | null>(null)

  // ── Derived: pure render, no side effects ─────────────────────────────────
  let _r = $derived.by(() => {
    if (!source.trim()) return { out: '', ms: 0, err: '' }
    const t0 = performance.now()
    try {
      const out = format === 'svg'
        ? latexToSvg(source, { theme, standalone: false })
        : latexToHtml(source, { theme, standalone: false, diagramBaseUrl: '/diagrams', renderMode })
      return { out, ms: Math.round(performance.now() - t0), err: '' }
    } catch (e: unknown) {
      return { out: '', ms: 0, err: e instanceof Error ? e.message : String(e) }
    }
  })
  let rendered   = $derived(_r.out)
  let renderTime = $derived(_r.ms)
  let errorMsg   = $derived(_r.err)
  // ── Paginate after DOM updates in paged mode ───────────────────────────────
  $effect(() => {
    const _ = rendered  // track dependency
    if (format === 'html' && renderMode === 'paged' && previewEl) {
      htexPaginate(previewEl)
    }
  })

  // ── File handling ──────────────────────────────────────────────────────────
  function onDragOver(e: DragEvent) { e.preventDefault(); isDragging = true }
  function onDragLeave(e: DragEvent) {
    if (!(e.currentTarget as Element)?.contains(e.relatedTarget as Node)) isDragging = false
  }
  async function onDrop(e: DragEvent) {
    e.preventDefault(); isDragging = false
    const file = e.dataTransfer?.files?.[0]; if (!file) return
    fileName = file.name; source = await file.text()
  }
  async function onFileInput(e: Event) {
    const file = (e.target as HTMLInputElement).files?.[0]; if (!file) return
    fileName = file.name; source = await file.text()
  }
  function download() {
    if (!rendered) return
    const ext  = format === 'svg' ? 'svg' : 'html'
    const mime = format === 'svg' ? 'image/svg+xml' : 'text/html'
    const full = format === 'html'
      ? latexToHtml(source, { theme, standalone: true, diagramBaseUrl: '/diagrams', renderMode })
      : latexToSvg(source, { theme, standalone: true })
    const a = Object.assign(document.createElement('a'), {
      href: URL.createObjectURL(new Blob([full], { type: mime })),
      download: (fileName.replace(/\.[^.]+$/, '') || 'document') + '.' + ext,
    })
    a.click(); URL.revokeObjectURL(a.href)
  }
  async function copyOutput() {
    if (!rendered) return
    await navigator.clipboard.writeText(rendered)
    copied = true; setTimeout(() => { copied = false }, 1500)
  }
</script>

<style>
  /* ── App chrome ────────────────────────────────────────────────────────── */
  :global(*, *::before, *::after) { box-sizing: border-box; margin: 0; padding: 0; }
  :global(body) {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
    background: #0f1117;
    color: #e2e8f0;
    height: 100vh;
    overflow: hidden;
  }

  .shell {
    display: grid;
    grid-template-rows: 48px 1fr;
    height: 100vh;
    overflow: hidden;
  }

  /* ── Header ── */
  header {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0 1rem;
    background: #0d1117;
    border-bottom: 1px solid #21262d;
    overflow: hidden;
    flex-shrink: 0;
  }
  .logo {
    font-size: 1rem;
    font-weight: 800;
    letter-spacing: -0.5px;
    color: #f0f6fc;
    white-space: nowrap;
    flex-shrink: 0;
  }
  .logo em { font-style: normal; font-weight: 400; color: #8b949e; font-size: 0.9em; }
  .badge {
    font-size: 0.6rem;
    font-weight: 700;
    padding: 0.1rem 0.4rem;
    border-radius: 3px;
    background: #1f3a5f;
    color: #58a6ff;
    flex-shrink: 0;
  }
  .stat { font-size: 0.7rem; color: #6e7681; white-space: nowrap; }
  .spacer { flex: 1; }
  .controls { display: flex; gap: 0.4rem; align-items: center; flex-shrink: 0; }

  .pill {
    display: flex;
    background: #161b22;
    border-radius: 5px;
    padding: 2px;
    border: 1px solid #30363d;
    gap: 1px;
  }
  .pill button {
    padding: 0.15rem 0.55rem;
    border: none; border-radius: 3px;
    font-size: 0.7rem; font-weight: 600;
    cursor: pointer;
    background: transparent; color: #8b949e;
    transition: all 0.1s; white-space: nowrap;
  }
  .pill button.on        { background: #238636; color: #fff; }
  .pill button.on.format { background: #1f6feb; }

  .btn {
    padding: 0.2rem 0.65rem; border-radius: 5px;
    border: 1px solid #30363d; background: #21262d; color: #c9d1d9;
    font-size: 0.7rem; font-weight: 600; cursor: pointer;
    white-space: nowrap; transition: border-color 0.1s, background 0.1s;
  }
  .btn:hover:not(:disabled) { border-color: #58a6ff; background: #1c2128; }
  .btn:disabled { opacity: 0.35; cursor: default; }
  .btn.accent { background: #1f6feb; border-color: #1f6feb; color: #fff; }
  .btn.accent:hover:not(:disabled) { background: #388bfd; }

  /* ── Workspace ── */
  .workspace {
    display: grid;
    grid-template-columns: 1fr 1fr;
    overflow: hidden;
    min-height: 0;
  }

  /* ── Left: editor ── */
  .pane {
    display: flex; flex-direction: column;
    overflow: hidden; border-right: 1px solid #21262d; min-height: 0;
  }
  .pane-bar {
    display: flex; align-items: center; justify-content: space-between;
    padding: 0 0.75rem; height: 32px;
    background: #0d1117; border-bottom: 1px solid #21262d;
    font-size: 0.65rem; font-weight: 700; color: #6e7681;
    text-transform: uppercase; letter-spacing: 0.08em; flex-shrink: 0;
  }
  .file-chip {
    background: #1f3a5f; color: #79c0ff;
    padding: 0.08rem 0.35rem; border-radius: 3px;
    font-size: 0.62rem; font-weight: 600;
    text-transform: none; letter-spacing: 0;
  }
  .drop-hint {
    padding: 0 0.75rem; height: 28px;
    display: flex; align-items: center; gap: 0.5rem;
    background: #0d1117; border-bottom: 1px solid #21262d;
    font-size: 0.68rem; color: #6e7681; flex-shrink: 0;
  }
  .drop-hint code { font-family: monospace; color: #8b949e; }
  .drop-hint label { color: #58a6ff; cursor: pointer; font-weight: 600; }
  .drop-hint label:hover { text-decoration: underline; }

  .editor-wrap {
    position: relative; flex: 1; overflow: hidden; min-height: 0;
  }
  .drag-overlay {
    position: absolute; inset: 0;
    background: rgba(31,111,235,0.12); border: 2px dashed #1f6feb;
    display: flex; align-items: center; justify-content: center;
    font-size: 1rem; font-weight: 700; color: #58a6ff;
    z-index: 10; pointer-events: none;
  }
  textarea {
    width: 100%; height: 100%;
    background: #0d1117; border: none; outline: none; resize: none;
    padding: 0.75rem 1rem;
    font-family: 'Fira Code', 'Cascadia Code', 'JetBrains Mono', 'SF Mono', monospace;
    font-size: 0.78rem; line-height: 1.6; color: #c9d1d9; tab-size: 2;
  }
  textarea::placeholder { color: #30363d; }

  /* ── Right: preview — PDF viewer aesthetic ── */
  .preview-pane {
    display: flex; flex-direction: column;
    overflow: hidden; min-height: 0;
    background: #404040;
  }
  /* Canvas mode: white background to match document */
  .preview-pane.canvas-mode { background: #ffffff; }

  .preview-scroll {
    flex: 1; overflow: auto; min-height: 0;
    /* The engine's .htex-document handles all layout and padding */
  }
  /* Engine output fills the scroll area */
  .preview-scroll :global(.htex-document) {
    min-height: 100%;
    width: 100%;
  }
  /* SVG output: centre on grey canvas */
  .svg-canvas {
    padding: 2rem;
    background: #404040;
    min-height: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .svg-canvas :global(svg) {
    max-width: 760px;
    width: 100%;
    height: auto;
    background: #fff;
    box-shadow: 0 0 0 1px rgba(0,0,0,0.15), 0 4px 20px rgba(0,0,0,0.4);
  }

  /* Error */
  .error-box {
    background: rgba(248,81,73,0.1); border: 1px solid rgba(248,81,73,0.3);
    border-radius: 6px; padding: 1rem; color: #ff7b72;
    font-family: monospace; font-size: 0.8rem; white-space: pre-wrap; line-height: 1.5;
    margin: 2rem auto; max-width: 760px;
  }
  .empty {
    display: flex; flex-direction: column;
    align-items: center; justify-content: center;
    height: 100%; min-height: 300px; gap: 0.5rem; color: #888;
  }
  .empty-icon { font-size: 2rem; }
  .empty-text { font-size: 0.8rem; }
</style>

<div class="shell">
  <!-- ── Header ── -->
  <header>
    <div class="logo">htex <em>/ svelte</em></div>
    <span class="badge">Svelte 5 · Runes</span>
    {#if source.trim()}
      <span class="stat">{renderTime}ms · {source.length.toLocaleString()} chars</span>
    {/if}
    <div class="spacer"></div>
    <div class="controls">
      <div class="pill">
        <button class="format" class:on={format === 'html'} onclick={() => format = 'html'}>HTML</button>
        <button class="format" class:on={format === 'svg'}  onclick={() => format = 'svg'}>SVG</button>
      </div>
      {#if format === 'html'}
      <div class="pill">
        <button class:on={renderMode === 'canvas'} onclick={() => renderMode = 'canvas'}>⬜ Canvas</button>
        <button class:on={renderMode === 'paged'}  onclick={() => renderMode = 'paged'}>📄 Pages</button>
      </div>
      {/if}
      <div class="pill">
        <button class:on={theme === 'light'} onclick={() => theme = 'light'}>☀ Light</button>
        <button class:on={theme === 'dark'}  onclick={() => theme = 'dark'}>🌙 Dark</button>
      </div>
      <button class="btn" onclick={copyOutput} disabled={!rendered}>
        {copied ? '✓ Copied' : '⎘ Copy'}
      </button>
      <button class="btn accent" onclick={download} disabled={!rendered}>
        ↓ {format.toUpperCase()}
      </button>
    </div>
  </header>

  <!-- ── Workspace ── -->
  <div class="workspace">

    <!-- Left: LaTeX source editor -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="pane" role="region" aria-label="LaTeX source editor"
      ondragover={onDragOver} ondragleave={onDragLeave} ondrop={onDrop}>
      <div class="pane-bar">
        LaTeX Source
        {#if fileName}<span class="file-chip">📄 {fileName}</span>{/if}
      </div>
      <div class="drop-hint">
        📂 Drop a <code>.tex</code> file here, or
        <label>browse<input type="file" accept=".tex,.txt" style="display:none" onchange={onFileInput}/></label>
        to open
      </div>
      <div class="editor-wrap">
        {#if isDragging}
          <div class="drag-overlay">📄 Drop .tex file here</div>
        {/if}
        <textarea
          bind:value={source}
          placeholder="Paste or type LaTeX here…"
          spellcheck="false"
          autocorrect="off"
          autocapitalize="off"
        ></textarea>
      </div>
    </div>

    <!-- Right: paged/canvas preview — engine manages layout -->
    <div class="preview-pane" class:canvas-mode={renderMode === 'canvas' && format === 'html'}>
      <div class="pane-bar">
        Preview — {format === 'html' ? (renderMode === 'paged' ? 'PAGES' : 'CANVAS') : 'SVG'}
        {#if fileName}<span class="file-chip">{fileName}</span>{/if}
      </div>
      <div class="preview-scroll" bind:this={previewEl}>
        {#if errorMsg}
          <div class="error-box">⚠ Render error:

{errorMsg}</div>
        {:else if rendered}
          {#if format === 'svg'}
            <!-- SVG: centre on grey canvas -->
            <div class="svg-canvas">{@html rendered}</div>
          {:else}
            <!-- HTML: engine wraps pages in .htex-document 	 .htex-page -->
            {@html rendered}
          {/if}
        {:else}
          <div class="empty">
            <div class="empty-icon">📄</div>
            <div class="empty-text">Rendered document appears here</div>
          </div>
        {/if}
      </div>
    </div>

  </div>
</div>
